title: R-tutorials
email: your-email@domain.com
description: r-tutorials and code examples
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kchafen
github_username:  khafen74
author: Konrad Hafen

# Build settings
markdown: kramdown

# Choosing "default" layout means we don't need a "layout:default" in all our 
# front matter
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

exclude:
    -src
    -config.yml

layouts_dir: src/_layouts
includes_dir: src/_includes
